config/routes.rb
  resources :probations do
    collection do
      get :probation_balance
      get :show_probationer
      get :transaction_history
      get :active_list
      post :disable_sentence_info
      match :posting_report, as: :posting_report, via: [:get, :post]
    end
    resources :probation_payments, path: 'payments', except: :index
  end
  
  ####################################
  # Detective Menu Routes
  ####################################
  scope 'investigations' do
    resources :invest_crimes, path: 'crimes', only: :index
    resources :invest_criminals, path: 'criminals', only: :index
    resources :invest_reports, path: 'reports', only: :index
    resources :invest_vehicles, path: 'vehicles', only: :index
    resources :invest_photos, path: 'photos', only: :index
  end
  resources :investigations do
    match :upload_photos, as: :upload_photos, on: :member, via: [:get, :post]
    resources :invest_notes, path: 'notes', except: [:index, :show]
    resources :invest_crimes, path: 'crimes', except: :index do
      resources :invest_notes, path: 'notes', except: [:index, :show]
    end
    resources :invest_criminals, path: 'criminals', except: :index do
      post :update_person, on: :collection
      resources :invest_notes, path: 'notes', except: [:index, :show]
    end
    resources :invest_reports, path: 'reports', except: :index do
      get :print_report, on: :member
      resources :invest_notes, path: 'notes', except: [:index, :show]
    end
    resources :invest_vehicles, path: 'vehicles', except: :index do
      resources :invest_notes, path: 'notes', except: [:index, :show]
    end
    resources :invest_photos, path: 'photos', except: :index do
      match :photo, action: :investigation_photo, as: :photo, on: :member, via: [:get, :post]
      resources :invest_notes, path: 'notes', except: [:index, :show]
    end
  end
  
  ####################################
  # Dispatch Menu Routes
  ####################################
  resources :calls do
    post :new_case_no, on: :member
    get :call_sheet, on: :member
    get :shift_report, on: :collection
  end
  resources :forbids do
    get :forbid_form, on: :member
    post :update_person, on: :collection
  end
  resources :histories, only: [:index, :show, :destroy]
  scope 'pawns' do
    resources :pawn_item_types, path: 'item_types'
  end
  resources :pawns
  resources :signal_codes do
    collection do
      get :signals
      get :validate
    end
  end
  resources :warrants do
    match :photo, as: :photo, on: :member, via: [:get, :post]
    collection do
      get :list_form
      get :photo_album
      post :update_person
    end
  end
  
  ####################################
  # Enforcement Menu Routes
  ####################################
  resources :case_notes do
    get :show_case, on: :collection
  end
  resources :citations
  resources :damages
  resources :evidences do
    member do
      match :photo, as: :photo, via: [:get, :post]
      get :change_location
    end
    get :inventory, on: :collection
  end
  resources :offenses do
    member do
      match :upload_photos, as: :upload_photos, via: [:get, :post]
      get :offense_report
    end
    resources :offense_photos, path: 'photos', except: :index do
      match :photo, as: :photo, on: :member, via: [:get, :post]
    end
  end
  resources :patrols do
    collection do
      get :patrol_summary
      get :patrol_activity
      post :autofill_shift_info
      post :autofill_officer_info
    end
  end
  resources :stolens
  resources :transports do
    get :voucher, on: :member
  end
  
  
  ####################################
  # Jail Menu Routes
  ####################################
  resources :arrests do
    member do
      get :print_72
      get :print_48
      get :id_card
      post :rebook
      match :seventytwo, as: :seventytwo, via: [:get, :post]
    end
    get :arrest_summary, on: :collection
  end
  resources :docs, except: [:new, :create]
  resources :jails do
    resources :bookings do
      member do
        match :temp_release_out, as: :temp_release_out, via: [:get, :post]
        post :temp_release_in
        get :arraignment_notice
        get :time_log
        post :toggle_goodtime
        post :clear_release
        get :jail_card
        match :release, as: :release, via: [:get, :post]
      end
      collection do
        get :photo_album
        get :problems
        get :problem_list
        get :list_form
        get :release_report
        get :in_jail
        get :ssa_report
        get :fcs_report
        get :billing_headcount
        get :month_billing
      end
      resources :holds, except: :index do
        member do
          get :clear
          put :clear_update
          post :toggle_bill
          post :clear_release
          get :adjustment
          put :adjustment_update
        end
      end
      resources :medicals, except: :index do
        get :medical_form, on: :member
      end
      resources :transfers, except: :index do
        post :update_transfer, on: :collection
      end
      resources :visitors, except: :index
    end
    resources :absents do
      member do
        get :checklist
        post :leave
        post :come_back
        post :copy
      end
    end
    resources :commissaries do
      collection do
        get :fund_balance
        match :posting_report, action: :posting_report, via: [:get, :post]
        get :sales_sheet
        get :transaction_report
      end
    end
    resources :commissary_items do
      get :sales_sheet, on: :collection
    end
    resources :holds, only: :index
    resources :transfers, only: :index
    resources :visitors, only: :index do
      member do 
        post :sign_out
        post :reset
      end
    end
  end
  
  ####################################
  # User Menu Routes
  ####################################
  # User Messages
  # Legacy Holdover from RestfulEasyMessages plugin
  controller :messages do
    scope 'user/:user_id' do
      scope 'message' do
        match ':id/print', action: :print_message, as: :print_message, via: :post
        match 'print_digest', action: :print_digest, as: :print_digest, via: :post
        match 'destroy_selected', action: :destroy_selected, as: :destroy_selected, via: :post
        match 'select_messages', action: :select_messages, as: :select_messages, via: :post
        match 'inbox', action: :inbox, as: :inbox_user_messages, via: :get
        match 'outbox', action: :outbox, as: :outbox_user_messages, via: :get
        match 'trashbin', action: :trashbin, as: :trashbin_user_messages, via: :get
        match 'new', action: :new, as: :new_user_message, via: :get
        match ':id/edit', action: :edit, as: :edit_user_message, via: :get
        match ':id/reply', action: :reply, as: :reply_user_message, via: :get
        match ':id', action: :show, as: :user_message, via: :get
        match ':id', action: :update, via: :put
        match ':id', action: :destroy, via: :delete
      end
      match 'messages', action: :index, as: :user_messages, via: :get
      match 'messages', action: :create, via: :post
    end
  end
  controller :users do
    scope 'my' do
      match :photo, as: :my_photo, via: [:get, :post]
      match :preferences, action: :edit_settings, as: :my_preferences, via: [:get, :post]
    end
    match :login, as: :login, via: [:get, :post]
    match :logout, as: :logout, via: [:get, :post]
    match :change_password, as: :change_password, via: [:get, :post]
  end
  
  ####################################
  # Utilities Menu Routes
  ####################################
  resources :announcements do
    get :toggle, on: :member
    get :all, on: :collection
  end
  resources :events
  resources :external_links do
    get :all, on: :collection
  end
  resources :fax_covers do
    get :fax_cover, on: :member
  end
  resources :statutes do
    get :validate_charge, on: :collection
  end
  
  ####################################
  # Admin Menu Routes
  ####################################
  resources :activities, only: [:index]
  controller :database do
    scope 'database' do
      post :clear_cases
      post :clear_sessions
    end
    get :databases, action: :index, as: :databases
  end
  resources :groups
  # Jails resources - see Jail Menu Routes
  resources :message_logs, only: [:index, :show]
  controller :site_configurations do
    scope 'config' do
      get :main, action: :site_main, as: :site_main
      match 'main/edit', action: :edit_site_main, as: :edit_site_main, via: [:get, :post]
      get :admin, action: :site_admin, as: :site_admin
      match 'admin/edit', action: :edit_site_admin, as: :edit_site_admin, via: [:get, :post]
      get :jail, action: :site_jail, as: :site_jail
      match 'jail/edit', action: :edit_site_jail, as: :edit_site_jail, via: [:get, :post]
      get :court, action: :site_court, as: :site_court
      match 'court/edit', action: :edit_site_court, as: :edit_site_court, via: [:get, :post]
      get :dispatch, action: :site_dispatch, as: :site_dispatch
      match 'dispatch/edit', action: :edit_site_dispatch, as: :edit_site_dispatch, via: [:get, :post]
      get :enforcement, action: :site_enforcement, as: :site_enforcement
      match 'enforcement/edit', action: :edit_site_enforcement, as: :edit_site_enforcement, via: [:get, :post]
      get :detective, action: :site_detective, as: :site_detective
      match 'detective/edit', action: :edit_site_detective, as: :edit_site_detective, via: [:get, :post]
      post :upload_logo
      post :upload_ceo_img
      post :upload_header_left_img
      post :upload_header_right_img
    end
  end
  resources :users do
    member do
      post :expire
      post :toggle
      post :reset
      match :photo, as: :photo, via: [:get, :post]
    end
    get :photo_album, on: :collection
  end
  
  controller :root do
    get :tools
    post :h_to_hdmy
    get :get_calendar
    get ':action', action: :index

app/models/commissary.rb
class Commissary < ActiveRecord::Base
  
  ## Associations #############################################
  
  belongs_to :creator, class_name: 'User', foreign_key: 'created_by'
  belongs_to :updater, class_name: 'User', foreign_key: 'updated_by'
  belongs_to :person, inverse_of: :commissaries
  belongs_to :jail, inverse_of: :commissaries
  
  ## Attributes #############################################
  
  attr_accessor :officer_id
  
  ## Scopes #############################################
  
  scope :unposted, -> { where report_datetime: nil }
  scope :posted_on, ->(posting_time) { where(report_datetime: posting_time) }
  scope :deposits, -> { where 'commissaries.deposit > 0' }
  scope :withdrawals, -> { where 'withdraw > 0' }
  scope :by_name, -> { includes(:person).order('people.family_name, people.given_name, commissaries.id') }
  scope :by_date, -> { order :transaction_date }
  scope :between, ->(start, stop) { AppUtils.for_daterange self, :transaction_date, start: start, stop: stop, date: true }
  scope :on_or_before, ->(date) { AppUtils.for_daterange self, :transaction_date, stop: date, date: true }
  scope :for_balance, -> { joins(:person).select('commissaries.person_id, SUM(commissaries.deposit - commissaries.withdraw) AS balance, commissaries.jail_id').group('commissaries.person_id').having("commissaries.balance != 0") }
  scope :belonging_to_person, ->(p_id) { includes(:person).where(person_id: p_id) }
  scope :belonging_to_jail, ->(j) { where jail_id: j }
  
  ## Callbacks #############################################
  
  before_save :check_creator
  before_validation :check_amounts, :lookup_officers
  before_destroy :check_destroyable

  ## Validations #############################################
  
  validates_presence_of :officer
  validates_date :transaction_date
  validates_numericality_of :deposit, :withdraw, greater_than_or_equal_to: 0, less_than: 10 ** 10
  validates_person :person_id
  validates_jail :jail_id

  ## Constants #############################################
  
  CommissaryType = ['Adjustment', 'Sales', 'Deposit', 'Medical', 'Refund'].freeze
  
  ## Class Methods #############################################
  
  def self.base_perms
    :view_commissary
  end
  
  def self.desc
    'Jail Commissary Records'
  end
  
  def self.posting_dates(jail)
    select('DISTINCT report_datetime').order(report_datetime: :desc).where(["report_datetime IS NOT NULL AND jail_id = ?",jail]).limit(10).all.collect{|c| [AppUtils.format_date(c.report_datetime),c.report_datetime]}
  end
  
  ## Instance Methods #############################################
  
  def reasons_not_destroyable
    report_datetime? ? "Transaction Posted" : nil
  end
  
  private
  
  ## Private Instance Methods #############################################
  
  def check_amounts
    retval = true
    unless (withdraw? && withdraw > 0) || (deposit? && deposit > 0)
      self.errors.add(:base, "Must enter either a withdraw amount or a deposit amount!")
      retval = false
    end
    if (withdraw? && withdraw > 0) && (deposit? && deposit > 0)
      self.errors.add(:base, "Must enter a withdraw amount or a deposit amount, not both!")
      retval = false
    end
    if withdraw? && withdraw < 0
      self.errors.add(:withdraw, "cannot be negative!")
      retval = false
    end
    if deposit? && deposit < 0
      self.errors.add(:deposit, "cannot be negative!")
      retval = false
    end
    retval
  end

  def check_destroyable
    reasons_not_destroyable.nil?
  end
  
  def lookup_officers
    unless officer_id.blank?
      if ofc = Contact.find_by_id(officer_id)
        self.officer = ofc.sort_name
        self.officer_badge = ofc.badge_no
        self.officer_unit = ofc.unit
      end
      self.officer_id = nil
    end
    true
  end
end

# == Schema Information
#
# Table name: commissaries
#
#  id               :integer          not null, primary key
#  person_id        :integer          not null
#  officer          :string(255)      default(""), not null
#  officer_unit     :string(255)      default(""), not null
#  deposit          :decimal(12, 2)   default(0.0), not null
#  withdraw         :decimal(12, 2)   default(0.0), not null
#  created_by       :integer          default(1)
#  updated_by       :integer          default(1)
#  created_at       :datetime
#  updated_at       :datetime
#  officer_badge    :string(255)      default(""), not null
#  report_datetime  :datetime
#  receipt_no       :string(255)      default(""), not null
#  memo             :string(255)      default(""), not null
#  transaction_date :date
#  jail_id          :integer          not null
#  category         :string(255)      default(""), not null
#
# Indexes
#
#  index_commissaries_on_booking_id  (person_id)
#  index_commissaries_on_created_by  (created_by)
#  index_commissaries_on_jail_id     (jail_id)
#  index_commissaries_on_updated_by  (updated_by)
#
# Foreign Keys
#
#  commissaries_created_by_fk  (created_by => users.id)
#  commissaries_jail_id_fk     (jail_id => jails.id)
#  commissaries_person_id_fk   (person_id => people.id)
#  commissaries_updated_by_fk  (updated_by => users.id)
#

app/views/commissaries/_commissary.html.erb
<% trans_net = (commissary.deposit > 0 ? commissary.deposit : -commissary.withdraw) %>
<%= list_partial(object: [commissary.jail, commissary]) do %>
  <%= list_partial_line(first: true) do %>
    <%= list_partial_id('Commissary', commissary.id) %>
    <%= list_partial_item(AppUtils.format_date(commissary.transaction_date)) %>
    <%= list_partial_item(commissary.category) %>
    <% unless @end_balance.nil? %>
      <%= list_partial_item(number_to_currency(@end_balance), right: true, money: true) %>
      <% @end_balance -= trans_net %>
    <% end %>
    <%= list_partial_item(number_to_currency(trans_net), right: true, money: true) %>
  <% end %>
  
  <%= list_partial_line do %>
    <%= list_partial_item('By:', AppUtils.show_contact(commissary, field: :officer)) %>
    <% if commissary.memo? %>
      <%= list_partial_item('Memo:', commissary.memo) %>
    <% end %>
    <% if commissary.receipt_no? %>
      <%= list_partial_item('Receipt:', commissary.receipt_no) %>
    <% end %>
    <% if commissary.report_datetime? %>
      <%= list_partial_item('Posted:', AppUtils.format_date(commissary.report_datetime), color: :red) %>
    <% end %>
  <% end %>
<% end %>

app/views/commissaries/_form.html.erb
<%= form_for [@jail, @commissary] do |f| %>
  <%= display_errors(@commissary) %>
  
  <%= hidden_field_tag(:person_id, @person.id) %>

  <%= field_set_tag 'Transaction', class: 'edit-form' do %>
    <%= f.hidden_field(:person_id) %>
    <%= edit_row('Inmate:', "#{AppUtils.show_person(@person)} #{@person.bookings.empty? ? '' : (@person.bookings.last.release_datetime? ? '(Not Currently Booked!)' : '' )}", class: 'bold large') %>
    <%= edit_row("Date:", required: true) do %>
      <%= f.date_field(:transaction_date) %>
      <%= field_spacer %>
      <%= required %><b>Transaction Type:</b> <%= f.select(:category, get_opts("Commissary Type", allow_nil: true)) %>
    <% end %>
    <%= f.edit_row_officer(:officer, 'Officers', required: true) %>

    <h4>Details</h4>
    <%= edit_row('Available Balance:', number_to_currency(@person.commissary_balance)) %>
    <% tt = 'Either a Deposit or a Withdrawal is required.  You cannot do both in a single transaction.' %>
    <%= edit_row("Deposit:", tooltip: tt) do %>
      <%= f.money_field(:deposit) %>
      <%= field_spacer %>
      &larr; OR &rarr;
      <%= field_spacer %>
      <b><%= with_tooltip("Withdraw:",tt) %></b> <%= f.money_field(:withdraw) %>
    <% end %>
    <%= f.edit_row_text(:receipt_no, size: 25) %>
    <%= f.edit_row_text(:memo, size: 30) %>
  <% end %>

  <%= form_buttons %>
<% end %>
<%= set_focus_to_id('commissary_transaction_date') %>

app/views/commissaries/edit.html.erb
<%= tip(std_help) %>
<%= render 'form' %>

app/views/commissaries/index.html.erb
<%= do_paged_index(list_title: 'Unposted Transactions') %>

<%= report_table("Reports") do %>
  <% tt = 'To generate this report for one inmate, enter their <b>Person ID</b>. If you leave <b>Person ID</b> blank (---) the report will be for the entire Jail.' %>
  <%= report_row("Transaction Report", tooltip: tt) do %>
    <form action="<%= transaction_report_jail_commissaries_path(@jail) %>">
      Report Type: <%= select_tag('status', options_for_select([['Detailed','detailed'],['Summary Only','summary']])) %>
      <%= field_spacer %>
      Person ID: <%= text_field_tag('person_id', "", size: 8) %>
      <br/>
      Start: <%= date_entry_tag('start_date', Date.today.beginning_of_month.to_s(:us)) %>
      <%= field_spacer %>
      Stop: <%= date_entry_tag('end_date', Date.today.to_s(:us)) %>
      <%= field_spacer %>
      <%= pdf_button %>
    </form>
  <% end %>
  
  <% tt = "Click PDF to print a list of all inmate balances for the current jail." %>
  <%= report_row("Fund Balance", tooltip: tt) do %>
    <form action="<%= fund_balance_jail_commissaries_path(@jail) %>" method='get'>
      <%= pdf_button %>
    </form>
  <% end %>

  <% tt = "This is the <b>Posting Preview</b> report and does not post transactions." %>
  <%= report_row("Posting Preview", tooltip: tt) do %>
    <form action="<%= posting_report_jail_commissaries_path(@jail) %>" method='get'>
      <%= hidden_field_tag('status', 'preview') %>
      <%= pdf_button %>
    </form>
  <% end %>
  
  <% tt = "To regenerate a prior posting report, select a posting date/time and click PDF." %>
  <%= report_row("Posting Reprint", tooltip: tt) do %>
    <form action="<%= posting_report_jail_commissaries_path(@jail) %>" method='get'>
      <%= hidden_field_tag('status', 'reprint') %>
      Date/Time: <%= select_tag('post_datetime', options_for_select(get_opts("Commissary Posting", jail_id: @jail.id))) %>
      <%= field_spacer %>
      <%= pdf_button(disabled: Commissary.posting_dates(@jail.id).empty?) %>
    </form>
  <% end %>
<% end %>

<% if can?(:update_commissary) %>
  <%= report_table("Functions") do %>
    <% tt = "Use this to enter new commissary transactions, or you can look up the person in People and use the <b>Commissary</b> button on that page." %>
    <%= report_row("New Transaction", tooltip: tt) do %>
      <form action="<%= new_jail_commissary_path(@jail) %>" method='get'>
        Person ID: <%= text_field_tag('person_id', "", size: 8) %>
        <%= field_spacer %>
        <%= submit_tag('Transaction', id: nil) %>
      </form>
    <% end %>
  
    <% tt = "This is the <b>Posting</b> report and <b>posts transactions</b>!<br/><br/><b>WARNING!</b> This is the actual posting report. It will mark all unposted transactions as posted. <b>This is not undoable!</b> Please make sure the <b>Preview</b> report (above) is correct before doing this!<br/><br/>Generating the Posting report will not update this screen. You need to do a screen refresh after posting or the old transactions will still be listed." %>
    <%= report_row("Post Transactions", tooltip: tt, dangerous: true) do %>
      <form action="<%= posting_report_jail_commissaries_path(@jail) %>" method='post'>
        <%= form_auth %>
        <%= hidden_field_tag('status', 'post') %>
        <%= pdf_button %>
      </form>
    <% end %>
  <% end %>
<% end %>

app/views/commissaries/new.html.erb
<%= tip(std_help) %>
<%= render 'form' %>

app/views/commissaries/show.html.erb
<%= tip("The <b>New</b> button at the bottom of the page will create a new commissary transaction for <b>this person</b>. To create a new commissary transaction for a different person, look them up in the people list then use the <b>Commissary</b> button on their page.") %>

<%= view_row('Inmate', AppUtils.show_person(@commissary.person), class: 'bold large') %>
<%= view_row('Date', AppUtils.format_date(@commissary.transaction_date), 'Transaction Type', @commissary.category) %>
<%= view_row('Officer', AppUtils.show_contact(@commissary, field: :officer)) %>
  
<h4>Details</h4>
<%= view_row('Deposited', number_to_currency(@commissary.deposit), 'Receipt No', @commissary.receipt_no) %>
<%= view_row('Withdrawn', number_to_currency(@commissary.withdraw), 'Memo', @commissary.memo) %>
<% if @commissary.report_datetime? %>
  <%= view_row('Posted', AppUtils.format_date(@commissary.report_datetime), class: 'red') %>
<% end %>

<%= link_bar %>