config/routes.rb
  resources :probations do
    collection do
      get :probation_balance
      get :show_probationer
      get :transaction_history
      get :active_list
      post :disable_sentence_info
      match :posting_report, as: :posting_report, via: [:get, :post]
    end
    resources :probation_payments, path: 'payments', except: :index
  end
  
  ####################################
  # Detective Menu Routes
  ####################################
  scope 'investigations' do
    resources :invest_crimes, path: 'crimes', only: :index
    resources :invest_criminals, path: 'criminals', only: :index
    resources :invest_reports, path: 'reports', only: :index
    resources :invest_vehicles, path: 'vehicles', only: :index
    resources :invest_photos, path: 'photos', only: :index
  end
  resources :investigations do
    match :upload_photos, as: :upload_photos, on: :member, via: [:get, :post]
    resources :invest_notes, path: 'notes', except: [:index, :show]
    resources :invest_crimes, path: 'crimes', except: :index do
      resources :invest_notes, path: 'notes', except: [:index, :show]
    end
    resources :invest_criminals, path: 'criminals', except: :index do
      post :update_person, on: :collection
      resources :invest_notes, path: 'notes', except: [:index, :show]
    end
    resources :invest_reports, path: 'reports', except: :index do
      get :print_report, on: :member
      resources :invest_notes, path: 'notes', except: [:index, :show]
    end
    resources :invest_vehicles, path: 'vehicles', except: :index do
      resources :invest_notes, path: 'notes', except: [:index, :show]
    end
    resources :invest_photos, path: 'photos', except: :index do
      match :photo, action: :investigation_photo, as: :photo, on: :member, via: [:get, :post]
      resources :invest_notes, path: 'notes', except: [:index, :show]
    end
  end
  
  ####################################
  # Dispatch Menu Routes
  ####################################
  resources :calls do
    post :new_case_no, on: :member
    get :call_sheet, on: :member
    get :shift_report, on: :collection
  end
  resources :forbids do
    get :forbid_form, on: :member
    post :update_person, on: :collection
  end
  resources :histories, only: [:index, :show, :destroy]
  scope 'pawns' do
    resources :pawn_item_types, path: 'item_types'
  end
  resources :pawns
  resources :signal_codes do
    collection do
      get :signals
      get :validate
    end
  end
  resources :warrants do
    match :photo, as: :photo, on: :member, via: [:get, :post]
    collection do
      get :list_form
      get :photo_album
      post :update_person
    end
  end
  
  ####################################
  # Enforcement Menu Routes
  ####################################
  resources :case_notes do
    get :show_case, on: :collection
  end
  resources :citations
  resources :damages
  resources :evidences do
    member do
      match :photo, as: :photo, via: [:get, :post]
      get :change_location
    end
    get :inventory, on: :collection
  end
  resources :offenses do
    member do
      match :upload_photos, as: :upload_photos, via: [:get, :post]
      get :offense_report
    end
    resources :offense_photos, path: 'photos', except: :index do
      match :photo, as: :photo, on: :member, via: [:get, :post]
    end
  end
  resources :patrols do
    collection do
      get :patrol_summary
      get :patrol_activity
      post :autofill_shift_info
      post :autofill_officer_info
    end
  end
  resources :stolens
  resources :transports do
    get :voucher, on: :member
  end
  
  
  ####################################
  # Jail Menu Routes
  ####################################
  resources :arrests do
    member do
      get :print_72
      get :print_48
      get :id_card
      post :rebook
      match :seventytwo, as: :seventytwo, via: [:get, :post]
    end
    get :arrest_summary, on: :collection
  end
  resources :docs, except: [:new, :create]
  resources :jails do
    resources :bookings do
      member do
        match :temp_release_out, as: :temp_release_out, via: [:get, :post]
        post :temp_release_in
        get :arraignment_notice
        get :time_log
        post :toggle_goodtime
        post :clear_release
        get :jail_card
        match :release, as: :release, via: [:get, :post]
      end
      collection do
        get :photo_album
        get :problems
        get :problem_list
        get :list_form
        get :release_report
        get :in_jail
        get :ssa_report
        get :fcs_report
        get :billing_headcount
        get :month_billing
      end
      resources :holds, except: :index do
        member do
          get :clear
          put :clear_update
          post :toggle_bill
          post :clear_release
          get :adjustment
          put :adjustment_update
        end
      end
      resources :medicals, except: :index do
        get :medical_form, on: :member
      end
      resources :transfers, except: :index do
        post :update_transfer, on: :collection
      end
      resources :visitors, except: :index
    end
    resources :absents do
      member do
        get :checklist
        post :leave
        post :come_back
        post :copy
      end
    end
    resources :commissaries do
      collection do
        get :fund_balance
        match :posting_report, action: :posting_report, via: [:get, :post]
        get :sales_sheet
        get :transaction_report
      end
    end
    resources :commissary_items do
      get :sales_sheet, on: :collection
    end
    resources :holds, only: :index
    resources :transfers, only: :index
    resources :visitors, only: :index do
      member do 
        post :sign_out
        post :reset
      end
    end
  end
  
  ####################################
  # User Menu Routes
  ####################################
  # User Messages
  # Legacy Holdover from RestfulEasyMessages plugin
  controller :messages do
    scope 'user/:user_id' do
      scope 'message' do
        match ':id/print', action: :print_message, as: :print_message, via: :post
        match 'print_digest', action: :print_digest, as: :print_digest, via: :post
        match 'destroy_selected', action: :destroy_selected, as: :destroy_selected, via: :post
        match 'select_messages', action: :select_messages, as: :select_messages, via: :post
        match 'inbox', action: :inbox, as: :inbox_user_messages, via: :get
        match 'outbox', action: :outbox, as: :outbox_user_messages, via: :get
        match 'trashbin', action: :trashbin, as: :trashbin_user_messages, via: :get
        match 'new', action: :new, as: :new_user_message, via: :get
        match ':id/edit', action: :edit, as: :edit_user_message, via: :get
        match ':id/reply', action: :reply, as: :reply_user_message, via: :get
        match ':id', action: :show, as: :user_message, via: :get
        match ':id', action: :update, via: :put
        match ':id', action: :destroy, via: :delete
      end
      match 'messages', action: :index, as: :user_messages, via: :get
      match 'messages', action: :create, via: :post
    end
  end
  controller :users do
    scope 'my' do
      match :photo, as: :my_photo, via: [:get, :post]
      match :preferences, action: :edit_settings, as: :my_preferences, via: [:get, :post]
    end
    match :login, as: :login, via: [:get, :post]
    match :logout, as: :logout, via: [:get, :post]
    match :change_password, as: :change_password, via: [:get, :post]
  end
  
  ####################################
  # Utilities Menu Routes
  ####################################
  resources :announcements do
    get :toggle, on: :member
    get :all, on: :collection
  end
  resources :events
  resources :external_links do
    get :all, on: :collection
  end
  resources :fax_covers do
    get :fax_cover, on: :member
  end
  resources :statutes do
    get :validate_charge, on: :collection
  end
  
  ####################################
  # Admin Menu Routes
  ####################################
  resources :activities, only: [:index]
  controller :database do
    scope 'database' do
      post :clear_cases
      post :clear_sessions
    end
    get :databases, action: :index, as: :databases
  end
  resources :groups
  # Jails resources - see Jail Menu Routes
  resources :message_logs, only: [:index, :show]
  controller :site_configurations do
    scope 'config' do
      get :main, action: :site_main, as: :site_main
      match 'main/edit', action: :edit_site_main, as: :edit_site_main, via: [:get, :post]
      get :admin, action: :site_admin, as: :site_admin
      match 'admin/edit', action: :edit_site_admin, as: :edit_site_admin, via: [:get, :post]
      get :jail, action: :site_jail, as: :site_jail
      match 'jail/edit', action: :edit_site_jail, as: :edit_site_jail, via: [:get, :post]
      get :court, action: :site_court, as: :site_court
      match 'court/edit', action: :edit_site_court, as: :edit_site_court, via: [:get, :post]
      get :dispatch, action: :site_dispatch, as: :site_dispatch
      match 'dispatch/edit', action: :edit_site_dispatch, as: :edit_site_dispatch, via: [:get, :post]
      get :enforcement, action: :site_enforcement, as: :site_enforcement
      match 'enforcement/edit', action: :edit_site_enforcement, as: :edit_site_enforcement, via: [:get, :post]
      get :detective, action: :site_detective, as: :site_detective
      match 'detective/edit', action: :edit_site_detective, as: :edit_site_detective, via: [:get, :post]
      post :upload_logo
      post :upload_ceo_img
      post :upload_header_left_img
      post :upload_header_right_img
    end
  end
  resources :users do
    member do
      post :expire
      post :toggle
      post :reset
      match :photo, as: :photo, via: [:get, :post]
    end
    get :photo_album, on: :collection
  end
  
  controller :root do
    get :tools
    post :h_to_hdmy
    get :get_calendar
    get ':action', action: :index

app/views/holds/_filter.html.erb
<%= filter_help(date: true) %>
<%= filter_text_row(:id, size: 8, header: 'Hold:', placeholder: 'ID') %>
<%= filter_text_row(:booking_id, size: 8, header: 'Booking:', placeholder: 'ID') %>
<%= filter_text_row(:arrest_id, size: 8, header: 'Arrest:', placeholder: 'ID') %>
<%= filter_date_range_row(:hold_date, header: 'Hold Date:') %>
<%= filter_text_row(:hold_type, size: 20) %>
<%= filter_boolean_row(:doc) %>
<% if can?(:update_billing) %>
  <%= filter_boolean_row(:doc_billable) %>
<% end %>
<%= filter_contact_row(:hold_by) %>
<%= filter_date_range_row(:cleared_date, header: 'Cleared Date:') %>
<%= filter_text_row(:cleared_because, size: 20) %>
<%= filter_contact_row(:cleared_by) %>
<%= filter_text_row(:explanation, size: 80) %>
<%= filter_text_row(:remarks, size: 80) %>

app/views/holds/_form.html.erb
<%= form_for [@jail, @booking, @hold] do |f| %>
  <%= display_errors(@hold) %>
  
  <%= field_set_tag 'Hold', class: 'edit-form' do %>
    <%= edit_row('Person:', AppUtils.show_person(@hold.booking.person), class: 'large bold') %>
    <%= edit_row('Date/Time:', required: true) do %>
      <%= f.datetime_field(:hold_datetime) %>
      <%= field_spacer %>
      <% if @hold.new_record? || @hold.hold_type.blank? %>
        <%= required %><b>Hold Type:</b> <%= f.select(:hold_type, get_opts('Hold Type', allow_nil: true)) %>
      <% else %>
        <b>Hold Type:</b> <%= @hold.hold_type %><%= field_spacer %>(You cannot change this)
      <% end %>
    <% end %>
    <%= f.edit_row_officer(:hold_by, 'Officers', header: 'Placed By:', required: true) %>
    <% tt = 'For Fines/Costs holds, <b>Can Pay</b> is required and is the total amount of fines and/or court costs required to be released.<br/><br/>For Bondable, Hold for City, Hold for Other Agency and for Probation holds, <b>Can Pay</b> is required and is the bond amount set by the Judge or Agency.' %>
    <%= f.edit_row_money(:fines, header: 'Can Pay:', tooltip: tt) %>

    <h4>Sentence Information</h4>
    <% tt = '<b>Sentence</b> is in Hours.<br/><br/>It is required for Fines/Costs holds.' %>
    <%= edit_row('Sentence:', tooltip: tt) do %>
      <%= f.text_field(:hours_total, size: 8) %>
      <%= field_spacer %>
      <% tt = '<b>Time Served Credit</b> is in Hours.' %>
      <%= with_tooltip('Time Served Credit:', tt) %> <%= f.text_field(:hours_time_served, size: 8) %>
      <%= field_spacer %>
      <% tt = 'If <b>Deny Goodtime</b> is checked, this hold will never accumulate goodtime, regardless of the <b>Goodtime</b> setting in Booking.' %>
      <%= f.check_box(:deny_goodtime, tag: "#{with_tooltip('Deny Goodtime', tt)}") %>
    <% end %>
    <% tt = 'All of these fields are <b>hours</b>. If you need to adjust these values and do not want to deal with hours, please use the <b>Adjustment</b> feature. It will allow you to enter adjustments in hours, days, months and years.' %>
    <%= edit_row("Accumulated:", tooltip: tt) do %>
      Hours Served: <%= f.text_field(:hours_served, size: 8) %>
      <%= field_spacer %>
      Hours Goodtime: <%= f.text_field(:hours_goodtime, size: 8) %>
    <% end %>

    <h4>Agency Information</h4>
    <% tt = '<b>Agency</b> is required for Hold for City, Hold for Other Agency and Fines/Costs hold types.' %>
    <%= f.edit_row_agency(:agency, 'Agencies', tooltip: tt) %>

    <%= f.textile_field(:remarks, tooltip: remark_note) %>
  <% end %>
  
  <%= form_buttons %>
<% end %>
<%= set_focus_to_id('hold_hold_datetime') %>

app/views/holds/_hold.html.erb
<% if can?(:update_booking) && !hold.cleared_datetime? %>
  <div class='list-buttons'>
    <% unless hold.hold_type.blank? %>
      <% if hold.can_bond? %>
        <% if hold.satisfied? %>
          <div><%= button_to_function('Clear', "window.location.href='#{clear_jail_booking_hold_path(hold.jail, hold.booking, hold, cause: 'Bonded')}'") %></div>
        <% else %>
          <div><%= button_to_function('Add Bond',"window.location.href='#{new_bond_path(hold_id: hold.id)}'") %></div>
          <div><%= button_to_function('Clear WO Bond',"window.location.href='#{clear_jail_booking_hold_path(hold.jail, hold.booking, hold, cause: 'Manual Release')}'") %></div>
        <% end %>
      <% else %>
        <% if hold.hold_type == '72 Hour' %>
          <div><%= button_to_function('Clear',"window.location.href='#{seventytwo_arrest_path(id: hold.arrest.id, booking_id: hold.booking.id)}'") %></div>
        <% elsif hold.hold_type == 'Temporary Transfer' || hold.hold_type == 'Temporary Housing' %>
          <div><%= button_to('Clear', new_jail_booking_transfer_path(hold.booking.jail, hold.booking), style: 'padding-top:2px;', method: :get) %></div>
          <% if hold.hold_type == 'Temporary Transfer' && can?(:update_billing) %>
            <div><%= button_to((hold.other_billable? ? "Not Billable" : "Billable"), toggle_bill_jail_booking_hold_path(hold.jail, hold.booking, hold), style: 'padding-top:2px;', method: :post) %></div>
          <% end %>
        <% elsif hold.hold_type == 'Temporary Release' %>
          <div><%= button_to('Return', temp_release_in_jail_booking_path(hold.booking.jail, hold.booking, hold_id: hold.id), method: :post) %></div>
        <% else %>
          <div><%= button_to_function('Clear',"window.location.href='#{clear_jail_booking_hold_path(hold.jail, hold.booking, hold)}'") %></div>
        <% end %>
      <% end %>
    <% end %>
  </div>
<% end %>
<%= list_partial(object: [hold.jail, hold.booking, hold]) do %>
  <%= list_partial_line(first: true) do %>
    <%= list_partial_id('Hold', hold.id) %>
    <% if hold.legacy? %>
      <%= list_partial_item(icon('legacy')) %>
    <% end %>
    <% if hold.cleared_datetime? %>
      <%= list_partial_item(hold.hold_type, color: :green) %>
    <% else %>
      <%= list_partial_item(hold.hold_type, color: :red) %>
    <% end %>
    <%= list_partial_item('Date:', AppUtils.format_date(hold.hold_datetime)) %>
    
    <% if can?(:update_billing) && hold.doc_billable? %>
      <%= list_partial_item(icon('doc-billable')) %>
    <% elsif hold.doc? %>
      <%= list_partial_item(icon('doc')) %>
    <% end %>
    <% unless hold.cleared_datetime? %>
      <% if hold.expired? %>
        <%= list_partial_item(icon('expired')) %>
      <% end %>
      <% if hold.hold_type == "Serving Sentence" || hold.hold_type == "Fines/Costs" %>
        <% if hold.hours_total == 0 %>
          <%= list_partial_item(icon('pending')) %>
        <% else %>
          <% hrem = hold.hours_remaining %>
          <% if hrem <= 0 %>
            <%= list_partial_item(icon('time-served')) %>
          <% else %>
            <%= list_partial_item(AppUtils.hours_to_string(hrem), class: 'hours-remaining', bold: true) %>
            <% if hold.active_blockers? %>
              <%= list_partial_item(icon('consecutive')) %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
    
    <% if hold.cleared_datetime? %>
      <%= list_partial_item(icon('cleared', style: 'vertical-align:middle;'), right: true) %>
      <%= list_partial_item(AppUtils.format_date(hold.cleared_datetime)) %>
    <% elsif hold.fines? && hold.fines > 0 && hold.can_bond? && hold.satisfied? %>
      <%= list_partial_item('[Bond Amount Satisfied]', color: :green) %>
    <% end %>
  <% end %>
  
  <%= list_partial_line do %>
    <%= list_partial_item('By:', "#{hold.hold_by_unit} #{hold.hold_by}") %>
    <% unless hold.doc_record.nil? %>
      <%= list_partial_item('DOC:', hold.doc_record.id) %>
    <% end %>
    <% unless hold.transfer.nil? %>
      <%= list_partial_item('Transfer:', hold.transfer.id) %>
    <% end %>
    <% unless hold.sentence.nil? %>
      <%= list_partial_item('Sentence:', hold.sentence.id) %>
    <% end %>
    <% unless hold.revocation.nil? %>
      <%= list_partial_item('Revocation:', hold.revocation.id) %>
    <% end %>
    <% unless hold.probation.nil? %>
      <%= list_partial_item('Probation:', hold.probation.id) %>
    <% end %>
    <% unless hold.arrest.nil? %>
      <%= list_partial_item('Arrest:', hold.arrest.id) %>
    <% end %>
    <% unless controller.controller_name == 'bookings' %>
      <%= list_partial_item('Booking:', hold.booking_id) %>
    <% end %>
    <%= list_partial_item(hold.hold_reason_name, hold.hold_reason) %>
    <% if hold.hold_type == 'Temporary Transfer' && can?(:update_billing) %>
      <% if hold.other_billable? %>
        <%= list_partial_item('(Billable)', color: :green) %>
      <% else %>
        <%= list_partial_item('(Not Billable)', color: :red) %>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/holds/adjustment.html.erb
<%= tip(std_help) %>
<%= tip('Enter your adjustment and then click the <b>Preview</b> button. The hours shown will update with your adjustments. When you are satisfied that the numbers are correct, click <b>Submit</b> to actually save them.') %>

<%= form_for(@hold_adjustment, url: {action: 'adjustment_update', id: @hold.id}, method: :put) do |f| %>
  <%= display_errors(@hold_adjustment) %>
  
  <%= hidden_field_tag :booking_id, @booking.id %>
  <%= hidden_field_tag :jail_id, @jail.id %>

  <% tt = 'This form is used to make adjustments to the Hours Sentenced, Hours Served, Hours Goodtime and Hours Time Served fields on a Serving Sentence or Fines/Costs hold.' %>
  <%= field_set_tag with_tooltip("Adjustment",tt), class: 'edit-form' do %>
    <%= edit_row('Name:', AppUtils.show_person(@hold.booking.person)) %>
    <%= edit_row('Sentence Rem:') do %>
      <%= @hold.hours_remaining %> Hours (<%= AppUtils.hours_to_sentence(@hold.hours_remaining, returns: 'string') %>)
    <% end %>
    <hr/>
    <% tt = '<b>Total Sentence</b> is the actual hours the inmate is sentenced to serve.' %>
    <%= edit_row("Total Sentence:", tooltip: tt) do %>
      <% if @hold.hours_total.blank? %>
        <span class='red'>INVALID</span>
      <% else %>
        <%= @hold.hours_total %> Hours (<%= AppUtils.hours_to_sentence(@hold.hours_total, returns: 'string') %>)
      <% end %>
    <% end %>
    <%= edit_row("Add:") do %>
      <span><b>Hours:</b> <%= f.text_field(:plus_hours_total, size: 8) %></span>
      <span><b>Days:</b> <%= f.text_field(:plus_days_total, size: 8) %></span>
      <span><b>Months:</b> <%= f.text_field(:plus_months_total, size: 8) %></span>
      <span><b>Years:</b> <%= f.text_field(:plus_years_total, size: 8) %></span>
    <% end %>
    <%= edit_row("Subtract:") do %>
      <span><b>Hours:</b> <%= f.text_field(:minus_hours_total, size: 8) %></span>
      <span><b>Days:</b> <%= f.text_field(:minus_days_total, size: 8) %></span>
      <span><b>Months:</b> <%= f.text_field(:minus_months_total, size: 8) %></span>
      <span><b>Years:</b> <%= f.text_field(:minus_years_total, size: 8) %></span>
    <% end %>
    <hr/>
    <% tt = '<b>Hours Served</b> is the actual hours the inmate has served here on this sentence.' %>
    <%= edit_row("Hours Served:", tooltip: tt) do %>
      <% if @hold.hours_served.blank? %>
        <span class='red'>INVALID</span>
      <% else %>
        <%= @hold.hours_served %> (<%= AppUtils.hours_to_sentence(@hold.hours_served, returns: 'string') %>)
      <% end %>
    <% end %>
    <%= edit_row("Add:") do %>
      <span><b>Hours:</b> <%= f.text_field(:plus_hours_served, size: 8) %></span>
      <span><b>Days:</b> <%= f.text_field(:plus_days_served, size: 8) %></span>
      <span><b>Months:</b> <%= f.text_field(:plus_months_served, size: 8) %></span>
      <span><b>Years:</b> <%= f.text_field(:plus_years_served, size: 8) %></span>
    <% end %>
    <%= edit_row("Subtract:") do %>
      <span><b>Hours:</b> <%= f.text_field(:minus_hours_served, size: 8) %></span>
      <span><b>Days:</b> <%= f.text_field(:minus_days_served, size: 8) %></span>
      <span><b>Months:</b> <%= f.text_field(:minus_months_served, size: 8) %></span>
      <span><b>Years:</b> <%= f.text_field(:minus_years_served, size: 8) %></span>
    <% end %>
    <hr/>
    <% tt = "<b>Hours Goodtime</b> is the actual Good Time hours the inmate has collected at this facility for this sentence." %>
    <%= edit_row("Hours Goodtime:", tooltip: tt) do %>
      <% if @hold.hours_goodtime.blank? %>
        <span class='red'>INVALID</span>
      <% else %>
        <%= @hold.hours_goodtime.round %> (<%= AppUtils.hours_to_sentence(@hold.hours_goodtime, returns: 'string') %>)
      <% end %>
    <% end %>
    <%= edit_row("Add:") do %>
      <span><b>Hours:</b> <%= f.text_field(:plus_hours_goodtime, size: 8) %></span>
      <span><b>Days:</b> <%= f.text_field(:plus_days_goodtime, size: 8) %></span>
      <span><b>Months:</b> <%= f.text_field(:plus_months_goodtime, size: 8) %></span>
      <span><b>Years:</b> <%= f.text_field(:plus_years_goodtime, size: 8) %></span>
    <% end %>
    <%= edit_row("Subtract:") do %>
      <span><b>Hours:</b> <%= f.text_field(:minus_hours_goodtime, size: 8) %></span>
      <span><b>Days:</b> <%= f.text_field(:minus_days_goodtime, size: 8) %></span>
      <span><b>Months:</b> <%= f.text_field(:minus_months_goodtime, size: 8) %></span>
      <span><b>Years:</b> <%= f.text_field(:minus_years_goodtime, size: 8) %></span>
    <% end %>
    <hr/>
    <% tt = '<b>Time Served Credit</b> is the total number of hours granted by the court for time served prior to sentencing.' %>
    <%= edit_row("Time Served Credit:", tooltip: tt) do %>
      <% if @hold.hours_time_served.blank? %>
        <span class='red'>INVALID</span>
      <% else %>
        <%= @hold.hours_time_served %> (<%= AppUtils.hours_to_sentence(@hold.hours_time_served, returns: 'string') %>)
      <% end %>
    <% end %>
    <%= edit_row("Add:") do %>
      <span><b>Hours:</b> <%= f.text_field(:plus_hours_time_served, size: 8) %></span>
      <span><b>Days:</b> <%= f.text_field(:plus_days_time_served, size: 8) %></span>
      <span><b>Months:</b> <%= f.text_field(:plus_months_time_served, size: 8) %></span>
      <span><b>Years:</b> <%= f.text_field(:plus_years_time_served, size: 8) %></span>
    <% end %>
    <%= edit_row("Subtract:") do %>
      <span><b>Hours:</b> <%= f.text_field(:minus_hours_time_served, size: 8) %></span>
      <span><b>Days:</b> <%= f.text_field(:minus_days_time_served, size: 8) %></span>
      <span><b>Months:</b> <%= f.text_field(:minus_months_time_served, size: 8) %></span>
      <span><b>Years:</b> <%= f.text_field(:minus_years_time_served, size: 8) %></span>
    <% end %>
  <% end %>>

  <%= form_buttons(preview: true, popup: false) %>
<% end %>
<%= set_focus_to_id('hold_adjustment_plus_hours_total') %>

app/views/holds/clear.html.erb
<%= tip(std_help) %>
<%= tip(textile_help) %>

<%= form_for([@jail, @booking, @hold], url: {action: :clear_update, id: @hold.id}, method: :put) do |f| %>
  <%= display_errors(@hold) %>

  <%= field_set_tag "Clearing Information", class: 'edit-form' do %>
    <%= f.edit_row_datetime(:cleared_datetime, required: true, header: 'Cleared:') %>
    <%= f.edit_row_select(:cleared_because, 'Cleared Because', required: true) %>
    <%= f.edit_row_officer(:cleared_by, 'Officers', required: true) %>
    <%= f.edit_row_text(:explanation, size: 80, required: true) %>

    <h4><%= with_tooltip('Transfer Information','This information is required for transfers only.') %></h4>
    <%= f.edit_row_agency(:agency, 'Agencies') %>
    <%= f.edit_row_officer(:transfer_officer, 'Officers') %>

    <%= f.textile_field(:remarks, tooltip: remark_note) %>
  <% end %>
  
  <%= form_buttons %>
<% end %>
<%= set_focus_to_id('hold_cleared_datetime') %>

app/views/holds/edit.html.erb
<%= tip(std_help) %>
<%= tip(textile_help) %>
<%= render 'form' %>

app/views/holds/index.html.erb
<%= do_paged_index %>

app/views/holds/new.html.erb
<%= tip(std_help) %>
<%= tip(textile_help) %>
<%= render 'form' %>