config/routes.rb
Fiveo::Application.routes.draw do
  ####################################
  # Main Menu Routes
  ####################################
  resources :contacts do
    get :merge, on: :member
    collection do
      get :employee_list
      get :contact_list
    end
  end
  scope "forums" do
    resources :forum_topics, except: :index, path: :topics do
      member do
        get :subscribe
        get :unsubscribe
        put :toggle_hide
        put :toggle_lock
        put :toggle_pin
        post :move
      end
      resources :forum_posts, path: :posts
    end
    resources :forum_categories, except: :index, path: :categories
  end
  resources :forums do
    resources :forum_topics, except: :index, path: :topics do
      member do
        get :subscribe
        get :unsubscribe
        put :toggle_hide
        put :toggle_lock
        put :toggle_pin
      end
      resources :forum_posts, path: :posts
    end
  end
  resources :people do
    member do
      get :rap_sheet
      get :links
      post :verify_warrant
      post :warrant_exemption
      post :verify_forbid
      post :forbid_exemption
      match :merge, as: :merge, via: [:get, :post]
      match :front_mugshot, as: :front_mugshot, via: [:get, :post]
      match :side_mugshot, as: :side_mugshot, via: [:get, :post]
    end
    collection do
      get :photo_album
      post :choose
      get :pick_list
    end
    resources :medications
  end
  
  ####################################
  # Court Menu Routes
  ####################################
  resources :dispositions, except: [:new, :create, :destroy] do
    collection do
      get :status_update
      get :status_report
      post :forms
    end
  end
  resources :bonds do
    member do
      post :undo_recall_bond
      post :recall_bond
      post :finalize_bond
      post :unfinalize_bond
      get :bond_form
      get :add_to_queue
      get :remove_from_queue
    end
    collection do
      post :update_companies
      get :active_list
      get :list_form
      get :list_unfinalized
      get :unfinalized_pdf
    end
  end
  resources :court_costs
  resources :court_types
  resources :docket_types
  resources :dockets do
    get :link_charges, on: :member
    collection do
      get :link
      get :letters
      get :dockets
      post :do_link
      get :list_unprocessed
      get :clear_letter_queue
      post :validate
      post :validate_da_charge
    end
    resources :courts, except: :index do
      get :worksheets, on: :member
      resources :sentences, except: :index do
        post :force_processing, on: :member
      end
    end
    resources :revocations, except: :index do
      post :force_processing, on: :member
    end
  end
  resources :garnishments
  scope 'papers' do
    resources :paper_customers, path: 'customers' do
      post :toggle_customer, on: :member
      post :update_fees, on: :collection
      resources :paper_payments, path: 'payments', except: :index
    end
    resources :paper_types, path: 'types'
  end
  resources :papers do
    member do
      post :uninvoice
      get :info_sheet
      match :payment, as: :payment, via: [:get, :post]
      match :invoice, as: :invoice, via: [:get, :post]
    end
    collection do
      get :billing_status
      get :service_status
      get :history
      post :autofill_serve_to
      post :clear_prior
      post :autofill_suit_info
      post :autofill_customer_info
      post :autofill_paper_info
      post :autofill_served_to
      match :invoices, action: :invoice, as: :invoices, via: [:get, :post]
      match :posting_report, as: :posting_report, via: [:get, :post]
    end
  end
  resources :probations do
    collection do
      get :probation_balance
      get :show_probationer
      get :transaction_history
      get :active_list
      post :disable_sentence_info
      match :posting_report, as: :posting_report, via: [:get, :post]
    end
    resources :probation_payments, path: 'payments', except: :index
  end
  
  ####################################
  # Detective Menu Routes
  ####################################
  scope 'investigations' do
    resources :invest_crimes, path: 'crimes', only: :index
    resources :invest_criminals, path: 'criminals', only: :index
    resources :invest_reports, path: 'reports', only: :index
    resources :invest_vehicles, path: 'vehicles', only: :index
    resources :invest_photos, path: 'photos', only: :index
  end
  resources :investigations do
    match :upload_photos, as: :upload_photos, on: :member, via: [:get, :post]
    resources :invest_notes, path: 'notes', except: [:index, :show]
    resources :invest_crimes, path: 'crimes', except: :index do
      resources :invest_notes, path: 'notes', except: [:index, :show]
    end
    resources :invest_criminals, path: 'criminals', except: :index do
      post :update_person, on: :collection
      resources :invest_notes, path: 'notes', except: [:index, :show]
    end
    resources :invest_reports, path: 'reports', except: :index do
      get :print_report, on: :member
      resources :invest_notes, path: 'notes', except: [:index, :show]
    end
    resources :invest_vehicles, path: 'vehicles', except: :index do
      resources :invest_notes, path: 'notes', except: [:index, :show]
    end
    resources :invest_photos, path: 'photos', except: :index do
      match :photo, action: :investigation_photo, as: :photo, on: :member, via: [:get, :post]
      resources :invest_notes, path: 'notes', except: [:index, :show]
    end
  end
  
  ####################################
  # Dispatch Menu Routes
  ####################################
  resources :calls do
    post :new_case_no, on: :member
    get :call_sheet, on: :member
    get :shift_report, on: :collection
  end
  resources :forbids do
    get :forbid_form, on: :member
    post :update_person, on: :collection
  end
  resources :histories, only: [:index, :show, :destroy]
  scope 'pawns' do
    resources :pawn_item_types, path: 'item_types'
  end
  resources :pawns
  resources :signal_codes do
    collection do
      get :signals
      get :validate
    end
  end
  resources :warrants do
    match :photo, as: :photo, on: :member, via: [:get, :post]
    collection do
      get :list_form
      get :photo_album
      post :update_person
    end
  end
  
  ####################################
  # Enforcement Menu Routes
  ####################################
  resources :case_notes do
    get :show_case, on: :collection
  end
  resources :citations
  resources :damages
  resources :evidences do
    member do
      match :photo, as: :photo, via: [:get, :post]
      get :change_location
    end
    get :inventory, on: :collection
  end
  resources :offenses do
    member do
      match :upload_photos, as: :upload_photos, via: [:get, :post]
      get :offense_report
    end
    resources :offense_photos, path: 'photos', except: :index do
      match :photo, as: :photo, on: :member, via: [:get, :post]
    end
  end
  resources :patrols do
    collection do
      get :patrol_summary
      get :patrol_activity
      post :autofill_shift_info
      post :autofill_officer_info
    end
  end
  resources :stolens
  resources :transports do
    get :voucher, on: :member
  end
  
  
  ####################################
  # Jail Menu Routes
  ####################################
  resources :arrests do
    member do
      get :print_72
      get :print_48
      get :id_card
      post :rebook
      match :seventytwo, as: :seventytwo, via: [:get, :post]
    end
    get :arrest_summary, on: :collection
  end
  resources :docs, except: [:new, :create]
  resources :jails do
    resources :bookings do
      member do
        match :temp_release_out, as: :temp_release_out, via: [:get, :post]
        post :temp_release_in
        get :arraignment_notice
        get :time_log
        post :toggle_goodtime
        post :clear_release
        get :jail_card
        match :release, as: :release, via: [:get, :post]
      end
      collection do
        get :photo_album
        get :problems
        get :problem_list
        get :list_form
        get :release_report
        get :in_jail
        get :ssa_report
        get :fcs_report
        get :billing_headcount
        get :month_billing
      end
      resources :holds, except: :index do
        member do
          get :clear
          put :clear_update
          post :toggle_bill
          post :clear_release
          get :adjustment
          put :adjustment_update
        end
      end
      resources :medicals, except: :index do
        get :medical_form, on: :member
      end
      resources :transfers, except: :index do
        post :update_transfer, on: :collection
      end
      resources :visitors, except: :index
    end
    resources :absents do
      member do
        get :checklist
        post :leave
        post :come_back
        post :copy
      end
    end
    resources :commissaries do
      collection do
        get :fund_balance
        match :posting_report, action: :posting_report, via: [:get, :post]
        get :sales_sheet
        get :transaction_report
      end
    end
    resources :commissary_items do
      get :sales_sheet, on: :collection
    end
    resources :holds, only: :index
    resources :transfers, only: :index
    resources :visitors, only: :index do
      member do 
        post :sign_out
        post :reset
      end
    end
  end
  
  ####################################
  # User Menu Routes
  ####################################
  # User Messages
  # Legacy Holdover from RestfulEasyMessages plugin
  controller :messages do
    scope 'user/:user_id' do
      scope 'message' do
        match ':id/print', action: :print_message, as: :print_message, via: :post
        match 'print_digest', action: :print_digest, as: :print_digest, via: :post
        match 'destroy_selected', action: :destroy_selected, as: :destroy_selected, via: :post

app/controllers/automated_messages_controller.rb
class AutomatedMessagesController < AbstractController::Base
  include AbstractController::Rendering
  include AbstractController::Helpers
  include AbstractController::Logger
  include Rails.application.routes.url_helpers
  
  helper ApplicationHelper
  
  self.view_paths = "app/views/automated_messages"
  
  # render notification message body
  def notify(object, style)
    @record = object
    @style = style
    render template: "#{object.class.to_s.tableize.singularize}_#{style}"
  end
end

app/views/automated_messages/arrest_new.html.erb
<b>This is an Automated Message</b>

<p>
  You are receiving this message because you checked the <b>Arrest: New</b>
  notification setting in your user preferences.
</p>

<p>
  <%= link_to(AppUtils.show_person(@record.person), @record.person) %>
  has been <%= link_to("arrested", @record) %>.
</p>

<p>
  <b>Arrest ID:</b> <%= @record.id %><br />
  <b>Arrest Date:</b> <%= AppUtils.format_date(@record.arrest_datetime) %><br />
  <b>Agency:</b> <%= @record.agency %><br />
  <% for o in @record.officers %>
    <b>Officer:</b> <%= AppUtils.show_contact(o, field: :officer) %><br />
  <% end %>
  <% if @record.dwi_test_officer? %>
    <b>DWI Test:</b> <%= AppUtils.show_contact(@record, field: :test_officer) %>
    <%= space(3) %>
    <b>Result:</b> <%= @record.dwi_test_results %><br />
  <% end %>
  <b>AFIS Number:</b> <%= @record.atn %><br />
  <b>Victim Notify?</b> <%= @record.victim_notify? ? "YES" : "NO" %><br />
  <% for c in @record.district_charges %>
    <b>District Charge:</b> (<%= c.count %>) <%= c.charge %><br />
  <% end %>
  <% for c in @record.city_charges %>
    <b>City Charge:</b> <%= c.agency %>: (<%= c.count %>) <%= c.charge %><br />
  <% end %>
  <% for c in @record.other_charges %>
    <b>Other Charge:</b> <%= c.agency %>: (<%= c.count %>) <%= c.charge %><br />
  <% end %>
  <% for w in @record.warrants %>
    <b>Warrant Served:</b> #<%= w.warrant_no %> (ID:<%= w.id %>): <%= w.jurisdiction.blank? ? 'Unknown' : w.jurisdiction %><br />
  <% end %>
</p>

app/views/automated_messages/booking_new.html.erb
<b>This is an Automated Message</b>

<p>
  You are receiving this message because you checked the <b>Booking: New</b>
  notification setting in your user preferences.
</p>

<p>
  <%= link_to(AppUtils.show_person(@record.person), @record.person) %>
  has been <%= link_to("booked", [@record.jail, @record]) %>.
</p>

<p>
  <b>Booking ID:</b> <%= @record.id %><br />
  <b>Jail:</b> <%= @record.jail.name %><br />
  <b>Booking Date/Time:</b> <%= AppUtils.format_date(@record.booking_datetime) %><br />
  <b>Booked By:</b> <%= AppUtils.show_contact(@record, field: :booking_officer) %>
</p>

app/views/automated_messages/booking_released.html.erb
<b>This is an Automated Message</b>

<p>
  You are receiving this message because you checked the <b>Booking: Released</b>
  notification setting in your user preferences.
</p>

<p>
  <%= link_to("Inmate " + AppUtils.show_person(@record.person), @record.person) %>
  has been released from <%= link_to("Booking ID " + @record.id.to_s, @record) %>
</p>

<p>
  <b>Booking ID:</b> <%= @record.id %><br />
  <b>Jail:</b> <%= @record.jail.name %><br />
  <b>Release Date:</b> <%= AppUtils.format_date(@record.release_datetime) %><br />
  <b>Release Reason:</b> <%= @record.released_because %><br />
  <b>Released By:</b> <%= AppUtils.show_contact(@record, field: :release_officer) %>
</p>

app/views/automated_messages/booking_reopened.html.erb
<b>This is an Automated Message</b>

<p>
  You are receiving this message because you checked the <b>Booking: New</b>
  notification setting in your user preferences.
</p>

<p>
  <%= link_to("Booking ID " + @record.id.to_s, @record) %> for
  <%= link_to("Person " + AppUtils.show_person(@record.person), @record.person) %>
  has been reopened.
</p>

<p>
  <b>Booking ID:</b> <%= @record.id %><br />
  <b>Jail:</b> <%= @record.jail.name %><br />
  <b>Original Booking Date:</b> <%= AppUtils.format_date(@record.booking_datetime) %><br />
  <b>Original Booked By:</b> <%= AppUtils.show_contact(@record, field: :booking_officer) %><br />
  <b>Reopened:</b> <%= AppUtils.format_date(@record.updated_at) %><br />
  <b>Reopened By:</b> <%= AppUtils.show_contact(@record.updater) %>
</p>

app/views/automated_messages/call_new.html.erb
<b>This is an Automated Message</b>

<p>
  You are receiving this message because you checked the <b>Call: New</b>
  notification setting in your user preferences.
</p>

<p>
  <%= link_to("Call Sheet ID: " + @record.id.to_s, @record) %>
  was created on <%= AppUtils.format_date(@record.call_datetime) %>
</p>

<p>
  <b>Case Number:</b> <%= @record.case_no %><br />
  <b>Signal:</b> <%= @record.signal_code %> <%= @record.signal_name %><br />
  <b>Dispatcher:</b> <%= AppUtils.show_contact(@record, field: :dispatcher) %>
</p>

<p>
  <b>People Involved:</b> <%= @record.subject_summary %>
</p>


<h3>Details</h3>
<%= raw simple_format(@record.details) %>

app/views/automated_messages/forbid_new.html.erb
<b>This is an Automated Message</b>

<p>
  You are receiving this message because you checked the <b>Forbid: New</b>
  notification setting in your user preferences.
</p>

<p>
  <%= link_to("Forbid ID: " + @record.id.to_s, @record) %>
  was <b>created</b> on <%= AppUtils.format_date(@record.request_date) %>
</p>

<p>
  <b>Case Number:</b> <%= @record.case_no %>
</p>

<p>
  <b>Forbidden Person:</b> <%= @record.person.nil? ? @record.sort_name : AppUtils.show_person(@record.person) %>
</p>
<blockquote>
  <%= @record.forbid_street %><br/>
  <%= @record.forbid_city_state_zip %></br/>
  Phone: <%= @record.forbid_phone %>
</blockquote>

<p>
  <b>Complainant:</b> <%= @record.complainant %>
</p>
<blockquote>
  <%= @record.comp_street %><br/>
  <%= @record.comp_city_state_zip %></br/>
  Phone: <%= @record.comp_phone %>
</blockquote>

<h3>Details</h3>
<%= raw simple_format(@record.details) %>

app/views/automated_messages/forbid_recalled.html.erb
<b>This is an Automated Message</b>

<p>
  You are receiving this message because you checked the <b>Forbid: Recalled</b>
  notification setting in your user preferences.
</p>

<p>
  <%= link_to("Forbid ID: " + @record.id.to_s, @record) %>
  was <b>recalled</b> on <%= AppUtils.format_date(@record.recall_date) %>
</p>

<p>
  <span style='font-size:125%;font-weight:bold;'>This forbid is no longer valid!</span>
</p>

<p>
  <b>Case Number:</b> <%= @record.case_no %>
</p>

<p>
  <b>Forbidden Person:</b> <%= @record.person.nil? ? @record.sort_name : AppUtils.show_person(@record.person) %>
</p>
<blockquote>
  <%= @record.forbid_street %><br/>
  <%= @record.forbid_city_state_zip %></br/>
  Phone: <%= @record.forbid_phone %>
</blockquote>

<p>
  <b>Complainant:</b> <%= @record.complainant %>
</p>
<blockquote>
  <%= @record.comp_street %><br/>
  <%= @record.comp_city_state_zip %></br/>
  Phone: <%= @record.comp_phone %>
</blockquote>

<h3>Details</h3>
<%= raw simple_format(@record.details) %>

app/views/automated_messages/forum_topic_updated.html.erb
A forum topic you have subscribed to has received a reply. You can view it here:

<%= forum_forum_topic_url(@record.forum_topic.forum_id, @record.forum_topic) %>

To unsubscribe from this topic, use the following link:
<%= unsubscribe_forum_forum_topic_url(@record.forum_topic.forum, @record.forum_topic) %>

app/views/automated_messages/jail_problems.html.erb
<% problems = @record.problems %>
<b>This is an Automated Message</b>

<p>
  You are receiving this message because you checked the <b>Booking: Problems</b>
  notification setting in your user preferences.
</p>

<p>
  <%= problems.size %> Booking Problems have been detected at
  <%= link_to(@record.name, jail_bookings_path(@record)) %>.
</p>

<p>
  <ul>
  <% for b in problems %>
    <li>Booking ID <%= b[0].id %>: <b><%= b[1] %></b></li>
  <% end %>
  </ul>
</p>

app/views/automated_messages/offense_new.html.erb
<b>This is an Automated Message</b>

<p>
  You are receiving this message because you checked the <b>Offense: New</b>
  notification setting in your user preferences.
</p>

<p>
  <%= link_to("Offense ID: " + @record.id.to_s, @record) %>
  was created on <%= AppUtils.format_date(@record.offense_datetime) %>
</p>

<p>
  <b>Case Number:</b> <%= @record.case_no %>
</p>

<p>
  <b>Officer:</b> <%= AppUtils.show_contact(@record, field: :officer) %>
</p>

<p>
  <b>People Involved:</b> <%= @record.involved_parties %>
</p>

<h3>Details</h3>
<%= raw simple_format(@record.details) %>

app/views/automated_messages/pawn_new.html.erb
<b>This is an Automated Message</b>

<p>
  You are receiving this message because you checked the <b>Pawn: New</b>
  notification setting in your user preferences.
</p>

<p>
  <%= link_to("Pawn ID: " + @record.id.to_s, @record) %>
  was created on <%= AppUtils.format_date(@record.ticket_date) %>.
</p>

<% if @record.case_no? %>
  <p>
    <b>Case Number:</b> <%= @record.case_no %>
  </p>
<% end %>

<p>
  <b>Company:</b> <%= @record.pawn_co %>
  <%= space(3) %>
  <b>Ticket Number:</b> <%= @record.ticket_no %>
</p>

<p>
  <b><%= @record.sort_name %></b> <%= @record.ticket_type %>
  the following items:
</p>
<blockquote>
  <%= @record.item_summary %>
</blockquote>

app/views/automated_messages/warrant_new.html.erb
<b>This is an Automated Message</b>

<p>
  You are receiving this message because you checked the <b>Warrant: New/Reactivated</b>
  notification setting in your user preferences.
</p>

<p>
  <%= link_to("Warrant No: " + @record.warrant_no, @record) %>
  was <b>added</b> on <%= AppUtils.format_date(@record.received_date) %>
</p>

<p>
  <b>Wanted:</b> <%= @record.sort_name %>
</p>

<p>
  <b>By:</b> <%= @record.jurisdiction %>
</p>

<p>
  <b>For:</b> <%= @record.charge_summary %>
</p>

app/views/automated_messages/warrant_reactivated.html.erb
<b>This is an Automated Message</b>

<p>
  You are receiving this message because you checked the <b>Warrant: New/Reactivated</b>
  notification setting in your user preferences.
</p>

<p>
  <%= link_to("Warrant No: " + @record.warrant_no, @record) %>
  was <b>reactivated</b> on <%= AppUtils.format_date(@record.received_date) %>
</p>

<p>
  <b>Wanted:</b> <%= @record.sort_name %>
</p>

<p>
  <b>By:</b> <%= @record.jurisdiction %>
</p>

<p>
  <b>For:</b> <%= @record.charge_summary %>
</p>

app/views/automated_messages/warrant_resolved.html.erb
<b>This is an Automated Message</b>

<p>
  You are receiving this message because you checked the <b>Warrant: Served/Recalled</b>
  notification setting in your user preferences.
</p>

<p>
  <%= link_to("Warrant No: " + @record.warrant_no, @record) %>
  was <b><%= @record.disposition %></b> on
  <%= AppUtils.format_date(@record.received_date) %>
</p>

<p>
  <span style='font-size:125%;font-weight:bold;'>This warrant is no longer active!</span>
</p>


<p>
  <b>Wanted:</b> <%= @record.sort_name %>
</p>

<p>
  <b>By:</b> <%= @record.jurisdiction %>
</p>

<p>
  <b>For:</b> <%= @record.charge_summary %>
</p>