config/routes.rb
Fiveo::Application.routes.draw do
  ####################################
  # Main Menu Routes
  ####################################
  resources :contacts do
    get :merge, on: :member
    collection do
      get :employee_list
      get :contact_list
    end
  end
  scope "forums" do
    resources :forum_topics, except: :index, path: :topics do
      member do
        get :subscribe
        get :unsubscribe
        put :toggle_hide
        put :toggle_lock
        put :toggle_pin
        post :move
      end
      resources :forum_posts, path: :posts
    end
    resources :forum_categories, except: :index, path: :categories
  end
  resources :forums do
    resources :forum_topics, except: :index, path: :topics do
      member do
        get :subscribe
        get :unsubscribe
        put :toggle_hide
        put :toggle_lock
        put :toggle_pin
      end
      resources :forum_posts, path: :posts
    end
  end
  resources :people do
    member do
      get :rap_sheet
      get :links
      post :verify_warrant
      post :warrant_exemption
      post :verify_forbid
      post :forbid_exemption
      match :merge, as: :merge, via: [:get, :post]
      match :front_mugshot, as: :front_mugshot, via: [:get, :post]
      match :side_mugshot, as: :side_mugshot, via: [:get, :post]
    end
    collection do
      get :photo_album
      post :choose
      get :pick_list
    end
    resources :medications
  end
  
  ####################################
  # Court Menu Routes
  ####################################
  resources :dispositions, except: [:new, :create, :destroy] do
    collection do
      get :status_update
      get :status_report
      post :forms
    end
  end
  resources :bonds do
    member do
      post :undo_recall_bond
      post :recall_bond
      post :finalize_bond
      post :unfinalize_bond
      get :bond_form
      get :add_to_queue
      get :remove_from_queue
    end
    collection do
      post :update_companies
      get :active_list
      get :list_form
      get :list_unfinalized
      get :unfinalized_pdf
    end
  end
  resources :court_costs
  resources :court_types
  resources :docket_types
  resources :dockets do
    get :link_charges, on: :member
    collection do
      get :link
      get :letters
      get :dockets
      post :do_link
      get :list_unprocessed
      get :clear_letter_queue
      post :validate
      post :validate_da_charge
    end
    resources :courts, except: :index do
      get :worksheets, on: :member
      resources :sentences, except: :index do
        post :force_processing, on: :member
      end
    end
    resources :revocations, except: :index do
      post :force_processing, on: :member
    end
  end
  resources :garnishments
  scope 'papers' do
    resources :paper_customers, path: 'customers' do
      post :toggle_customer, on: :member
      post :update_fees, on: :collection
      resources :paper_payments, path: 'payments', except: :index
    end
    resources :paper_types, path: 'types'
  end
  resources :papers do
    member do
      post :uninvoice
      get :info_sheet
      match :payment, as: :payment, via: [:get, :post]
      match :invoice, as: :invoice, via: [:get, :post]
    end
    collection do
      get :billing_status
      get :service_status
      get :history
      post :autofill_serve_to
      post :clear_prior
      post :autofill_suit_info
      post :autofill_customer_info
      post :autofill_paper_info
      post :autofill_served_to
      match :invoices, action: :invoice, as: :invoices, via: [:get, :post]
      match :posting_report, as: :posting_report, via: [:get, :post]
    end
  end
  resources :probations do
    collection do
      get :probation_balance
      get :show_probationer
      get :transaction_history
      get :active_list
      post :disable_sentence_info
      match :posting_report, as: :posting_report, via: [:get, :post]
    end
    resources :probation_payments, path: 'payments', except: :index
  end
  
  ####################################
  # Detective Menu Routes
  ####################################
  scope 'investigations' do
    resources :invest_crimes, path: 'crimes', only: :index
    resources :invest_criminals, path: 'criminals', only: :index
    resources :invest_reports, path: 'reports', only: :index
    resources :invest_vehicles, path: 'vehicles', only: :index
    resources :invest_photos, path: 'photos', only: :index
  end
  resources :investigations do
    match :upload_photos, as: :upload_photos, on: :member, via: [:get, :post]
    resources :invest_notes, path: 'notes', except: [:index, :show]
    resources :invest_crimes, path: 'crimes', except: :index do
      resources :invest_notes, path: 'notes', except: [:index, :show]
    end
    resources :invest_criminals, path: 'criminals', except: :index do
      post :update_person, on: :collection
      resources :invest_notes, path: 'notes', except: [:index, :show]
    end
    resources :invest_reports, path: 'reports', except: :index do
      get :print_report, on: :member
      resources :invest_notes, path: 'notes', except: [:index, :show]
    end
    resources :invest_vehicles, path: 'vehicles', except: :index do
      resources :invest_notes, path: 'notes', except: [:index, :show]
    end
    resources :invest_photos, path: 'photos', except: :index do
      match :photo, action: :investigation_photo, as: :photo, on: :member, via: [:get, :post]
      resources :invest_notes, path: 'notes', except: [:index, :show]
    end
  end
  
  ####################################
  # Dispatch Menu Routes
  ####################################
  resources :calls do
    post :new_case_no, on: :member
    get :call_sheet, on: :member
    get :shift_report, on: :collection
  end
  resources :forbids do
    get :forbid_form, on: :member
    post :update_person, on: :collection
  end
  resources :histories, only: [:index, :show, :destroy]
  scope 'pawns' do
    resources :pawn_item_types, path: 'item_types'
  end
  resources :pawns
  resources :signal_codes do
    collection do
      get :signals
      get :validate
    end
  end
  resources :warrants do
    match :photo, as: :photo, on: :member, via: [:get, :post]
    collection do
      get :list_form
      get :photo_album
      post :update_person
    end
  end
  
  ####################################
  # Enforcement Menu Routes
  ####################################
  resources :case_notes do
    get :show_case, on: :collection
  end
  resources :citations
  resources :damages
  resources :evidences do
    member do
      match :photo, as: :photo, via: [:get, :post]
      get :change_location
    end
    get :inventory, on: :collection
  end
  resources :offenses do
    member do
      match :upload_photos, as: :upload_photos, via: [:get, :post]
      get :offense_report
    end
    resources :offense_photos, path: 'photos', except: :index do
      match :photo, as: :photo, on: :member, via: [:get, :post]
    end
  end
  resources :patrols do
    collection do
      get :patrol_summary
      get :patrol_activity
      post :autofill_shift_info
      post :autofill_officer_info
    end
  end
  resources :stolens
  resources :transports do
    get :voucher, on: :member
  end
  
  
  ####################################
  # Jail Menu Routes
  ####################################
  resources :arrests do
    member do
      get :print_72
      get :print_48
      get :id_card
      post :rebook
      match :seventytwo, as: :seventytwo, via: [:get, :post]
    end
    get :arrest_summary, on: :collection
  end
  resources :docs, except: [:new, :create]
  resources :jails do
    resources :bookings do
      member do
        match :temp_release_out, as: :temp_release_out, via: [:get, :post]
        post :temp_release_in
        get :arraignment_notice
        get :time_log
        post :toggle_goodtime
        post :clear_release
        get :jail_card
        match :release, as: :release, via: [:get, :post]
      end
      collection do
        get :photo_album
        get :problems
        get :problem_list
        get :list_form
        get :release_report
        get :in_jail
        get :ssa_report
        get :fcs_report
        get :billing_headcount
        get :month_billing
      end
      resources :holds, except: :index do
        member do
          get :clear
          put :clear_update
          post :toggle_bill
          post :clear_release
          get :adjustment
          put :adjustment_update
        end
      end
      resources :medicals, except: :index do
        get :medical_form, on: :member
      end
      resources :transfers, except: :index do
        post :update_transfer, on: :collection
      end
      resources :visitors, except: :index
    end
    resources :absents do
      member do
        get :checklist
        post :leave
        post :come_back
        post :copy
      end
    end
    resources :commissaries do
      collection do
        get :fund_balance
        match :posting_report, action: :posting_report, via: [:get, :post]
        get :sales_sheet
        get :transaction_report
      end
    end
    resources :commissary_items do
      get :sales_sheet, on: :collection
    end
    resources :holds, only: :index
    resources :transfers, only: :index
    resources :visitors, only: :index do
      member do 
        post :sign_out
        post :reset
      end
    end
  end
  
  ####################################
  # User Menu Routes
  ####################################
  # User Messages
  # Legacy Holdover from RestfulEasyMessages plugin
  controller :messages do
    scope 'user/:user_id' do
      scope 'message' do
        match ':id/print', action: :print_message, as: :print_message, via: :post
        match 'print_digest', action: :print_digest, as: :print_digest, via: :post
        match 'destroy_selected', action: :destroy_selected, as: :destroy_selected, via: :post

app/models/paper_type.rb
class PaperType < ActiveRecord::Base
  belongs_to :creator, class_name: 'User', foreign_key: 'created_by'    # constraint with nullify
  belongs_to :updater, class_name: 'User', foreign_key: 'updated_by'    # constraint with nullify

  scope :by_name, -> { order :name }
  
  before_save :check_creator

  validates_presence_of :name
  validates_uniqueness_of :name
  validates_numericality_of :cost, greater_than_or_equal_to: 0, less_than: 10 ** 10

  ## Class Methods #############################################
  
  def self.desc
    "Paper Types"
  end
  
  def self.base_perms
    :update_papers
  end
  
  def self.names_for_select
    order('name').all.collect{|c| [c.name,c.id]}
  end
end

# == Schema Information
#
# Table name: paper_types
#
#  id         :integer          not null, primary key
#  name       :string(255)      default(""), not null
#  cost       :decimal(12, 2)   default(0.0), not null
#  created_by :integer          default(1)
#  updated_by :integer          default(1)
#  created_at :datetime
#  updated_at :datetime
#
# Indexes
#
#  index_paper_types_on_created_by  (created_by)
#  index_paper_types_on_updated_by  (updated_by)
#
# Foreign Keys
#
#  paper_types_created_by_fk  (created_by => users.id)
#  paper_types_updated_by_fk  (updated_by => users.id)
#

app/views/papers/_filter.html.erb
<%= filter_help %>
<%= filter_text_row(:id, size: 8, header: 'Paper:', placeholder: 'ID') %>
<%= filter_text_row(:paper_type, size: 20) %>
<%= filter_date_row(:court_date, header: 'Court Date:') %>
<%= filter_text_row(:suit_no) %>
<% tt = '<b>Name</b> will match in any of Plaintiff, Defendant, Serve To or Served To fields.' %>
<%= filter_text_row(:name, tooltip: tt) %>
<%= filter_boolean_row(:billable) %>
<%= filter_select_row(:paper_customer_id, 'Paper Customers', header: 'Customer:') %>
<%= filter_text_row(:remarks, size: 70) %>

app/views/papers/_form.html.erb
<%= form_for @paper do |f| %>
  <%= display_errors(@paper) %>

  <%= field_set_tag 'Paper', class: 'edit-form' do %>
    <%= edit_row("Suit/Docket No:", required: true) do %>
      <%= f.text_field(:suit_no, size: 20) %>
      <%= f.observe_field('paper_suit_no', url: autofill_suit_info_papers_path, with: 'suit') %>
    <% end %>
    <%= edit_row("Paper Type:", required: true) do %>
      <%= f.select(:paper_type_id, get_opts("Paper Type", allow_nil: true)) %>
      <%= arrow_spacer %>
      <%= @paper.paper_type %>
      <%= f.observe_field('paper_paper_type_id', url: autofill_paper_info_papers_path, with: 'paper_type_id') %>
    <% end %>
    <%= edit_row("Received:", required: true) do %>
      <%= f.date_field(:received_date) %>
      <%= field_spacer %>
      <b>Court Date:</b> <%= f.date_field(:court_date) %>
    <% end %>
    <%= edit_row("Plaintiff:", required: true) do %>
      <%= f.text_field(:plaintiff, size: 30) %>
      <%= field_spacer %>
      <% tt = "If you leave <b>Defendant</b> blank, it will automatically be filled in with the name you enter for <b>Serve To</b> below." %>
      <%= required %><b><%= with_tooltip("Defendant:", tt) %></b> <%= f.text_field(:defendant, size: 30) %>
    <% end %>
    <%= f.edit_row_text(:serve_to, size: 30, required: true) %>
    <%= f.observe_field('paper_serve_to', url: autofill_serve_to_papers_path, with: "'name=' + value + '&defendant=' + encodeURIComponent($('paper_defendant').value)") %>
    <%= edit_row("Address:") do %>
      <%= f.address_field(:street, nil, :city, :state, :zip) %>
      <span id='prior-status'>&nbsp;</span>
      <%= f.observe_field('paper_street', url: clear_prior_papers_path) %>
      <%= f.observe_field('paper_city', url: clear_prior_papers_path) %>
      <%= f.observe_field('paper_state', url: clear_prior_papers_path) %>
      <%= f.observe_field('paper_zip', url: clear_prior_papers_path) %>
    <% end %>
    <%= f.edit_row_phone(:phone) %>

    <% tt = "<b>Service Type</b> and <b>Officer</b> are required in order to invoice this paper.  Additionally, either <b>Served Date/Time</b> and <b>Served To</b> OR <b>Date Returned</b> and <b>Non-Service Reason</b> should be filled in prior to invoicing." %>
    <h4><%= with_tooltip("Service", tt) %></h4>
    <%= f.edit_row_select(:service_type, "Service Type", allow_nil: true) %>
    <%= f.observe_field('paper_service_type', url: autofill_served_to_papers_path, with: "'service_type=' + value + '&' + Form.Element.serialize('paper_serve_to')") %>
    <%= edit_row("Served:") do %>
      <%= f.datetime_field(:served_datetime) %>
      <%= field_spacer %>
      <b>Served To:</b> <%= f.text_field(:served_to, size: 30) %>
    <% end %>
    <%= edit_row("Returned:") do %>
      <%= f.date_field(:returned_date) %>
      <%= field_spacer %>
      <b>Reason:</b> <%= f.select(:noservice_type, get_opts("Noservice Type", allow_nil: true)) %>
      <%= field_spacer %>
      <%= f.text_field(:noservice_extra, size: 40, placeholder: 'Returned Comment') %>
    <% end %>
    <%= f.edit_row_officer(:officer, 'Officers') %>
    <% tt = "<b>Mileage</b> must be a number (cannot be blank).  If you are not charging mileage, set mileage to 0." %>
    <%= edit_row("Mileage:", tooltip: tt) do %>
      <%= f.text_field(:mileage, size: 6, placeholder: '9999.9') %>
      <%= field_spacer %>
      (Look Up On <%= link_to_function("MapQuest","lookupMapQuest($('paper_street').value,$('paper_city').value,$('paper_state').options[$('paper_state').options.selectedIndex].text,'#{SiteConfig.agency_street}','#{SiteConfig.agency_city}','#{SiteConfig.agency_state}')") %>)
    <% end %>

    <h4>Billing</h4>
    <%= edit_row("Customer:") do %>
      <% group_options = grouped_options_for_select([['Frequently Used', [['---',nil], *get_opts("Paper Customers Common")]],['Alphabetical', get_opts("Paper Customers")]], @paper.paper_customer_id) %>
      <%= select_tag('paper[paper_customer_id]', group_options, id: 'paper_paper_customer_id') %>
      <%= f.observe_field('paper_paper_customer_id', url: autofill_customer_info_papers_path, with: 'customer_id') %>
      <%= field_spacer %>
      <%= f.check_box(:billable, tag: 'Billable') %>
      <%= field_spacer %>
      <% tt = "If <b>Mileage Only</b> is checked, the paper service amount on the invoice will always be $0.00 regardless of the <b>Service Fee</b> setting below, and only mileage will be billed." %>
      <%= f.check_box(:mileage_only, tag: "#{with_tooltip('Mileage Only', tt)}") %>
    <% end %>
    <%= edit_row("Fees:") do %>
      <% tt = "<b>Service</b> is the amount to bill for serving this paper. If left blank, it will be filled in with the standard amount for this paper type." %>
      <%= with_tooltip("Service:", tt) %> <%= f.money_field(:service_fee) %>
      <%= field_spacer %>
      <% tt = "<b>No-Service</b> is the amount to bill when this paper cannot be served (unable to locate, etc).  If left blank, it will be filled in with the default value for this Customer." %>
      <%= with_tooltip("No-Service:", tt) %> <%= f.money_field(:noservice_fee) %>
      <%= field_spacer %>
      <% tt = "<b>Per Mile</b> is the amount charged per mile.  If left blank, it will be filled in with the default Per Mile Fee for this Customer. If mileage should not be billed for this paper, set the <b>Mileage</b> field above to 0 and leave this field at the default value." %>
      <%= with_tooltip("Per Mile:", tt) %> <%= f.money_field(:mileage_fee) %>
    <% end %>

    <% tt = 'These comments will appear on the Info Sheet.' %>
    <h4><%= with_tooltip("Comments", tt) %></h4>
    <%= f.text_area(:comments) %>

    <%= f.textile_field(:remarks, tooltip: remark_note) %>
  <% end %>

  <%= form_buttons %>
<% end %>
<%= set_focus_to_id('paper_suit_no') %>

app/views/papers/_paper.html.erb
<% line_color = paper.billable? ? nil : 'blue blue-bg' %>
<%= list_partial(object: paper, color: line_color) do %>
  <%= list_partial_line(first: true) do %>
    <%= list_partial_id('Paper', paper.id) %>
    <%= list_partial_item('Suit:', paper.suit_no) %>
    <%= list_partial_item('Type:', paper.paper_type) %>
    <%= list_partial_item('Serve To:', paper.serve_to) %>
  <% end %>
  
  <%= list_partial_line do %>
    <% unless paper.customer.nil? %>
      <%= list_partial_item('Customer:', paper.customer.name) %>
    <% end %>
    <%= list_partial_item('For Court:', AppUtils.format_date(paper.court_date)) %>
    <%= list_partial_item('Status:', paper.status.nil? ? "Done" : paper.status) %>
  <% end %>
<% end %>

app/views/papers/_unposted.html.erb
<%= list_partial(object: [unposted.customer, unposted]) do %>
  <%= list_partial_line(first: true) do %>
    <%= list_partial_item(unposted.id, idtag: true) %>
    <%= list_partial_item(AppUtils.format_date(unposted.transaction_date)) %>
    <%= list_partial_item('Customer:', unposted.customer.name) %>
    <%= list_partial_item('[' + number_to_money(unposted.payment) + ']', right: true, money: true) %>
    <%= list_partial_item(number_to_money(unposted.charge), right: true, money: true) %>
  <% end %>
  
  <% if unposted.memo? || unposted.receipt_no? || (unposted.report_datetime? && list_type == 'all') || unposted.paid_in_full? %>
    <%= list_partial_line do %>
      <% if unposted.report_datetime? && list_type == 'all' %>
        <%= list_partial_item('Posted:', AppUtils.format_date(unposted.report_datetime), color: :red) %>
      <% end %>
      <% if unposted.memo? %>
        <%= list_partial_item('Memo:', unposted.memo) %>
      <% end %>
      <% if unposted.receipt_no? %>
        <%= list_partial_item('Receipt:', unposted.receipt_no) %>
      <% end %>
      <% if unposted.paid_in_full? %>
        <%= list_partial_item('PAID IN FULL', right: true, color: :green) %>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/papers/autofill_customer_info.js.erb
$('#paper_noservice_fee').val("<%= @noservice %>");
$('#paper_mileage_fee').val("<%= @mileage %>");

app/views/papers/autofill_paper_info.js.erb
$('#paper_service_fee').val("<%= @service %>");

app/views/papers/autofill_serve_to.js.erb
<% unless @name.blank? %>
  $('#paper_name').val("<%= @name %>");
<% end %>
$('#paper_street').val("<%= @street %>");
$('#paper_city').val("<%= @city %>");
$('#paper_state').val("<%= @state %>");
$('#paper_zip').val("<%= @zip %>");
$('#paper_phone').val("<%= @phone %>");
$('#paper_mileage').val("<%= @mileage %>");
$('#paper_defendant').val("<%= @defendant %>");
$('#prior-status').html("<%= @prior %>");
$('#paper_street').select();

app/views/papers/autofill_served_to.js.erb
<% if @valid %>
  $('#paper_served_to').val("<%= @name %>");
<% end %>

app/views/papers/autofill_suit_info.js.erb
$('#paper_plaintiff').val("<%= @plaintiff %>");
$('#paper_defendant').val("<%= @defendant %>");
$('#paper_paper_customer_id').val("<%= @customer_id %>");

app/views/papers/clear_prior.js.erb
$('#prior-status').html("&nbsp;");

app/views/papers/edit.html.erb
<%= tip(std_help) %>
<%= render 'form' %>

app/views/papers/index.html.erb
<%= tip("Papers shown in blue are not billable.") %>
<%= do_paged_index %>

<%= do_list('Unposted Transactions', 'unposted', @payments, locals: {list_type: 'unposted'}) %>

<%= report_table("Reports") do %>
  <% tt = "Select a Court Date and click PDF to list the status of all papers for that court date." %>
  <%= report_row("Service Status", tooltip: tt) do %>
    <form action="<%= service_status_papers_path %>" method='get'>
      Court Date: <%= date_entry_tag('court_date', Date.today.to_s(:us)) %>
      <%= field_spacer %>
      <%= pdf_button %>
    </form>
  <% end %>
  
  <% tt = "Select a Customer and click PDF to list all billable papers for that customer.  If you leave the Customer set to blank (---) the report will be for <b>all customers</b>.  This does not generate invoices!" %>
  <%= report_row("Billable Papers", tooltip: tt) do %>
    <form action="<%= billing_status_papers_path %>" method='get'>
      <%= hidden_field_tag('status', 'billable') %>
      Customer: <%= select_tag('customer_id', "<option value=''>---</option>".html_safe + options_for_select(PaperCustomer.billable_names_for_select)) %>
      <%= field_spacer %>
      <%= pdf_button %>
    </form>
  <% end %>
  
  <% tt = "Select a Customer and click PDF to list all payable papers (outstanding invoices) for that customer. If you leave the Customer set to blank (---) the report will be for <b>all customers</b>.  This does not enter payments!" %>
  <%= report_row("Payable Papers", tooltip: tt) do %>
    <form action="<%= billing_status_papers_path %>" method='get'>
      <%= hidden_field_tag('status','payable') %>
      Customer: <%= select_tag('customer_id', "<option value=''>---</option>".html_safe + options_for_select(PaperCustomer.payable_names_for_select)) %>
      <%= field_spacer %>
      <%= pdf_button %>
    </form>
  <% end %>
  
  <% tt = "Select a Customer, a From: date and a To: date, then click PDF to print a history of all payments made by this customer during that period. To print all payments on file, make sure From: and To: are blank.  To print payments before a specific date, enter the date in To: and leave From: blank.  To print payments after a specific date, enter the date in From: and leave To: blank." %>
  <%= report_row("Payment History", tooltip: tt) do %>
    <form action="<%= history_papers_path %>" method='get'>
      Customer: <%= select_tag('customer_id', options_for_select(PaperCustomer.names_for_select(true))) %>
      <br/>
      From: <%= date_entry_tag('from_date', Date.today.beginning_of_month.to_s(:us)) %>
      <%= field_spacer %>
      To: <%= date_entry_tag('to_date', Date.today.to_s(:us)) %>
      <%= field_spacer %>
      <%= pdf_button %>
    </form>
  <% end %>
  
  <% tt = "Click PDF to generate the posting report <b>preview</b>. This will not post the transactions." %>
  <%= report_row("Posting Preview", button_to_function("PDF","window.location.href='#{posting_report_papers_path(status: 'preview')}'"), tooltip: tt) %>
  
  <% tt = "To reprint a prior posting report, select a posting date/time and click the PDF button." %>
  <%= report_row("Posting Reprint", tooltip: tt) do %>
    <form action="<%= posting_report_papers_path %>" method='get'>
      <%= hidden_field_tag('status', 'reprint') %>
      Posting Date: <%= select_tag('post_datetime', options_for_select(get_opts("Paper Posting"))) %>
      <%= field_spacer %>
      <%= pdf_button(disabled: PaperPayment.posting_dates.empty?) %>
    </form>
  <% end %>
<% end %>

<% if can?(:update_civil) %>
  <%= report_table("Functions") do %>
    <% tt = "Select a Customer and click Invoice to generate invoices for all billable papers for that customer." %>
    <%= report_row("Generate Invoices", tooltip: tt) do %>
      <% customers = PaperCustomer.billable_names_for_select %>
      <% if customers.empty? %>
        <% options = "<option value=''>No Billable Customers</option>" %>
      <% else %>
        <% options = options_for_select(customers) %>
      <% end %>
      <form action="<%= invoices_papers_path %>" method='post'>
        <%= form_auth %>
        Customer: <%= select_tag('customer_id', options) %>
        <%= field_spacer %>
        <%= submit_tag('Invoice', disabled: customers.empty?) %>
      </form>
    <% end %>

    <% tt = "Click PDF to generate the posting report. <b>WARNING!</b> This is the actual posting report. It will mark all unposted transactions as posted. <b>This is not undoable!</b> Please use the <b>Preview</b> report if you do not wish to post.<br/><br/>Printing the Posting report will not update this screen. You need to refresh the screen after posting or the old transactions will still be listed." %>
    <%= report_row("Post Transactions", button_to("PDF",posting_report_papers_path(status: 'post')), tooltip: tt, dangerous: true) %>

    <% tt = "<b>WARNING:</b> Use of this function will undo any custom fees you have specified for your customers.  Make sure this is what you want! Select which fees should be updated and click <b>Set To Default</b> to update selected fees to the Site Configuration values for <b>all Customers</b>. This function is intended to be used when Site Configuration has been updated with new default fee prices and you wish to update all existing customers accordingly.  If you wish to update a single customer, navigate to that customer record and use the button provided on that page." %>
    <%= report_row("Update Fees", tooltip: tt, dangerous: true) do %>
      <form action="<%= update_fees_paper_customers_path %>" method='post'>
        <%= form_auth %>
        <input type='radio' name='status' value='noservice' />No Service
        <%= field_spacer %>
        <input type='radio' name='status' value='mileage' />Mileage
        <%= field_spacer %>
        <input type='radio' name='status' value='all' checked='checked' />Both
        <%= field_spacer %>
        <%= submit_tag('Set To Default', id: nil, class: 'dangerous') %>
      </form>
    <% end %>
  <% end %>
<% end %>

app/views/papers/new.html.erb
<%= tip(std_help) %>
<%= render 'form' %>

app/views/papers/show.html.erb
<%= view_row('Suit or Docket No', @paper.suit_no, 'Paper Type', @paper.paper_type, class: 'large bold') %>
<%= view_row('Serve To', @paper.serve_to, 'Plaintiff', @paper.plaintiff) %>
<%= view_row('Address', @paper.address, 'Defendant', @paper.defendant) %>
<%= view_row('Phone', @paper.phone, 'Date Received', AppUtils.format_date(@paper.received_date)) %>
<%= view_row('Court Date', AppUtils.format_date(@paper.court_date)) %>

<h3>Service</h3>
<%= view_row('Service Type', @paper.service_type, 'Officer', !@paper.service_type.blank? ? AppUtils.show_contact(@paper, field: :officer) : "") %>
<%= view_row('Served To', @paper.served_to, 'Served Date/Time', AppUtils.format_date(@paper.served_datetime)) %>
<%= view_row('Date Returned', AppUtils.format_date(@paper.returned_date), 'Mileage', @paper.mileage) %>
<%= view_row('Non-Service Reason') do %>
  <%= @paper.noservice_type %>
  <%= @paper.noservice_extra? ? "(#{@paper.noservice_extra})" : "" %>
<% end %>
  
<h3>Billing</h3>
<%= view_row('Customer', @paper.customer.nil? ? 'N/A' : @paper.customer.name, 'Date Invoiced', @paper.invoice_datetime? ? AppUtils.format_date(@paper.invoice_datetime) : 'Not Yet Invoiced') %>
<%= view_row('Billable?', @paper.billable? ? (@paper.mileage_only? ? "Mileage Only" : "Yes") : "No", 'Amount Invoiced', @paper.invoice_datetime? ? number_to_currency(@paper.invoice_total) + (@paper.mileage_only? ? ' (Mileage Only)' : '') : "") %>
<%= view_row('Service Fee', number_to_currency(@paper.service_fee), 'Remaining Due', number_to_currency(@paper.invoice_due)) %>
<%= view_row('No-Service Fee', number_to_currency(@paper.noservice_fee), 'Paid In Full?', @paper.paid_in_full? ? 'Yes' : 'No') %>
<%= view_row('Per Mile Fee', number_to_currency(@paper.mileage_fee), 'Date Paid', @paper.invoice_datetime? ? (@paper.paid_date? ? AppUtils.format_date(@paper.paid_date) + (@paper.memo? ? " (#{@paper.memo})" : "") : 'Not Yet Paid') : 'N/A') %>

<%= view_text("Comments", @paper.comments, display: 'simple') %>
<%= view_text("Remarks", @paper.remarks) %>

<%= link_bar %>

<%= do_list('Transactions', 'unposted', @paper.payments.reverse, locals: {list_type: 'all'}) %>